import { useEffect, useState } from 'react'
import { ArrowRight, BookOpen, Boxes, FilePlus2, Images, Layers3, Plus } from 'lucide-react'
import type { Catalog } from '../../../../shared/types'
import { Button, Card } from '../../components/ui'

export function DashboardView({ openCatalogs, openProducts }: { openCatalogs: () => void; openProducts: () => void }) {
  const [catalogs, setCatalogs] = useState<Catalog[]>([])
  const [mediaCount, setMediaCount] = useState(0)
  useEffect(() => { void window.lechtom.catalog.list().then(setCatalogs); void window.lechtom.media.list().then((x) => setMediaCount(x.length)) }, [])
  return <><div className="page-heading dashboard-heading"><div><span className="eyebrow">TWOJE CENTRUM DOWODZENIA</span><h1>Dzień dobry 👋</h1><p>Twórz, organizuj i eksportuj katalogi produktowe LECHTOM.</p></div><Button onClick={openCatalogs}><Plus size={17}/> Nowy katalog</Button></div><div className="stats-grid"><Card className="stat-card"><div className="stat-icon stat-blue"><BookOpen size={21}/></div><span>Wszystkie katalogi</span><strong>{catalogs.length}</strong><small>W Twojej bibliotece</small></Card><Card className="stat-card"><div className="stat-icon stat-purple"><Layers3 size={21}/></div><span>Strony katalogów</span><strong>{catalogs.reduce((sum, x) => sum + x.pages.length, 0)}</strong><small>Łącznie we wszystkich katalogach</small></Card><Card className="stat-card"><div className="stat-icon stat-orange"><Images size={21}/></div><span>Pliki w mediach</span><strong>{mediaCount}</strong><small>Grafiki i logotypy</small></Card></div><div className="dashboard-grid"><Card className="recent-card"><div className="section-header"><div><h2>Ostatnie katalogi</h2><p>Szybki dostęp do Twoich projektów</p></div><button className="text-action" onClick={openCatalogs}>Zobacz wszystkie <ArrowRight size={15}/></button></div>{catalogs.length ? catalogs.slice(-4).reverse().map((catalog) => <div className="recent-row" key={catalog.id}><div className="recent-icon"><BookOpen size={19}/></div><div><strong>{catalog.name}</strong><small>{catalog.pages.length} stron · Edytowano {new Date(catalog.updatedAt).toLocaleDateString('pl-PL')}</small></div><span className="badge">Szkic</span></div>) : <div className="dashboard-empty"><div className="dashboard-empty-icon"><FilePlus2 size={26}/></div><h3>Jeszcze nie ma katalogów</h3><p>Utwórz pierwszy katalog, aby rozpocząć pracę.</p><Button variant="secondary" onClick={openCatalogs}>Przejdź do katalogów <ArrowRight size={16}/></Button></div>}</Card><Card className="quick-card"><div className="section-header"><div><h2>Szybkie działania</h2><p>Przejdź od razu do pracy</p></div></div><button className="quick-action" onClick={openCatalogs}><div className="quick-icon quick-blue"><Plus size={20}/></div><div><strong>Utwórz katalog</strong><small>Nowy projekt A4 od podstaw</small></div><ArrowRight size={17}/></button><button className="quick-action" onClick={openProducts}><div className="quick-icon quick-purple"><Boxes size={20}/></div><div><strong>Przeglądaj produkty ERP</strong><small>Wyszukaj produkty w bazie</small></div><ArrowRight size={17}/></button><div className="quick-note"><strong>Wskazówka</strong><p>Skonfiguruj połączenie z ERP w Ustawieniach, aby przeglądać produkty i dodawać je do katalogów.</p></div></Card></div></>
}
