import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Boxes, RefreshCw, Search, SlidersHorizontal } from 'lucide-react'
import type { PagedResult, Product } from '../../../../shared/types'
import { Button, Card, EmptyState, Input } from '../../components/ui'

export function ProductsView({ onSettings }: { onSettings: () => void }) {
  const [input, setInput] = useState('')
  const [query, setQuery] = useState('')
  const [page, setPage] = useState(1)
  const [result, setResult] = useState<PagedResult<Product> | null>(null)
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [reloadToken, setReloadToken] = useState(0)
  useEffect(() => { const timer = setTimeout(() => { setQuery(input); setPage(1) }, 300); return () => clearTimeout(timer) }, [input])
  useEffect(() => { let active = true; setLoading(true); void window.lechtom.erp.getProducts({ query, page, pageSize: 25 }).then((data) => { if (active) { setResult(data); setError('') } }).catch((e: Error) => { if (active) setError(e.message.includes('Skonfiguruj') ? 'Skonfiguruj połączenie w Ustawieniach ERP.' : 'Sprawdź połączenie i spróbuj ponownie.') }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [query, page, reloadToken])
  return <><div className="page-heading"><div><span className="eyebrow">ŹRÓDŁO DANYCH / COMARCH ERP XL</span><h1>Produkty ERP</h1><p>Przeglądaj produkty dostępne w firmowej bazie danych.</p></div><div className="heading-count"><Boxes size={18}/>{result ? `${result.total.toLocaleString('pl-PL')} produktów` : 'Baza produktów'}</div></div><Card className="table-card"><div className="table-toolbar"><div className="search-wrap"><Search size={18}/><Input value={input} onChange={(e) => setInput(e.target.value)} placeholder="Szukaj po nazwie lub kodzie produktu..." /></div><div className="toolbar-filter"><SlidersHorizontal size={16}/> Filtry producenta i kategorii po weryfikacji schematu ERP</div></div>{error ? <EmptyState icon={<Boxes size={29}/>} title="Brak połączenia z bazą ERP" description={error} action={<div className="empty-actions"><Button onClick={() => setReloadToken((x) => x + 1)}><RefreshCw size={15}/> Spróbuj ponownie</Button><Button variant="secondary" onClick={onSettings}>Ustawienia ERP</Button></div>} /> : <><div className="table-scroll"><table className="data-table"><thead><tr><th>Kod</th><th>EAN</th><th>Nazwa produktu</th><th>Producent / marka</th><th>JM</th><th>Przelicznik</th><th>VAT</th><th>Stan</th><th>Akcja</th></tr></thead><tbody>{result?.items.map((product) => <tr key={product.id}><td className="code-cell">{product.code}</td><td>{product.ean ?? '—'}</td><td className="name-cell">{product.name}</td><td>{product.manufacturer ?? '—'}</td><td><span className="unit-badge">{product.unit.displayUnit}</span></td><td>{product.unit.conversionFactor ?? '—'}</td><td>{product.vatRate == null ? '—' : `${product.vatRate}%`}</td><td>—</td><td><button className="row-action" title="Produkt jest gotowy do przypisania w edytorze katalogu"><ArrowRight size={16}/></button></td></tr>)}</tbody></table>{loading && <div className="table-loading">Ładowanie produktów...</div>}{!loading && result?.items.length === 0 && <div className="table-no-results">Nie znaleziono produktów.</div>}</div><div className="table-footer"><span>{result ? `Strona ${page} z ${Math.max(1, Math.ceil(result.total / 25))}` : '—'}</span><div><Button size="small" variant="secondary" disabled={page <= 1 || loading} onClick={() => setPage((x) => x - 1)}><ArrowLeft size={15}/> Poprzednia</Button><Button size="small" variant="secondary" disabled={!result || page * 25 >= result.total || loading} onClick={() => setPage((x) => x + 1)}>Następna <ArrowRight size={15}/></Button></div></div></>}</Card><p className="table-footnote">Dane produktów pochodzą bezpośrednio z ERP i są dostępne tylko do odczytu.</p></>
}
