import { useEffect, useState } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import { Database, Eye, EyeOff, FolderOpen, PlugZap, ShieldCheck } from 'lucide-react'
import type { AppSettings, ErpConfig } from '../../../../shared/types'
import { erpConfigSchema } from '../../../../shared/schemas'
import { Button, Card, Field, Input } from '../../components/ui'

export function SettingsView() {
  const { register, handleSubmit, reset, watch, setValue, formState: { errors } } = useForm<ErpConfig>({ resolver: zodResolver(erpConfigSchema), defaultValues: { server: '', database: '', authenticationType: 'sql', username: '', password: '', encrypt: true, trustServerCertificate: false } })
  const [settings, setSettings] = useState<AppSettings | null>(null)
  const [showPassword, setShowPassword] = useState(false)
  const [message, setMessage] = useState('')
  const [testing, setTesting] = useState(false)
  useEffect(() => { void window.lechtom.erp.getConfig().then((config) => { if (config) reset({ ...config, password: '' }) }); void window.lechtom.settings.get().then(setSettings) }, [reset])
  const save = handleSubmit(async (data) => { try { await window.lechtom.erp.saveConfig(data); setMessage('Konfiguracja została zapisana bezpiecznie.') } catch (error) { setMessage((error as Error).message) } })
  const test = handleSubmit(async (data) => { setTesting(true); try { const result = await window.lechtom.erp.testConnection(data); setMessage(`${result.message}: ${result.server} / ${result.database}`) } catch (error) { setMessage((error as Error).message || 'Brak połączenia z bazą ERP') } finally { setTesting(false) } })
  const chooseFolder = async () => { try { const result = await window.lechtom.settings.selectProjectsFolder(); if (result) setSettings(result) } catch (error) { setMessage((error as Error).message) } }
  return <><div className="page-heading"><div><span className="eyebrow">KONFIGURACJA</span><h1>Ustawienia</h1><p>Połączenie ERP i folder projektów.</p></div></div><div className="settings-layout"><Card className="settings-card"><div className="settings-section-head"><div className="settings-icon"><Database size={22}/></div><div><h2>Połączenie z ERP</h2><p>Microsoft SQL Server · Comarch ERP XL</p></div></div><div className="settings-divider"/><form onSubmit={save}><div className="form-grid"><Field label="Serwer"><Input {...register('server')} placeholder="SQL-SERVER\\INSTANCE"/>{errors.server && <small className="form-error">Podaj nazwę serwera</small>}</Field><Field label="Baza danych"><Input {...register('database')} placeholder="Nazwa bazy ERP"/>{errors.database && <small className="form-error">Podaj nazwę bazy</small>}</Field><Field label="Typ uwierzytelniania"><select className="input" {...register('authenticationType')}><option value="sql">SQL Server Authentication</option></select></Field><Field label="Użytkownik"><Input {...register('username')} autoComplete="username" placeholder="Konto tylko do odczytu"/>{errors.username && <small className="form-error">Podaj użytkownika</small>}</Field><Field label="Hasło" hint="Pozostaw puste, aby zachować zapisane hasło."><div className="password-wrap"><Input {...register('password')} type={showPassword ? 'text' : 'password'} autoComplete="new-password"/><button type="button" onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff size={17}/> : <Eye size={17}/>}</button></div></Field></div><div className="settings-checks"><label className="check-row"><input type="checkbox" checked={watch('encrypt')} onChange={(event) => setValue('encrypt', event.target.checked)}/><div><strong>Szyfruj połączenie</strong></div></label><label className="check-row"><input type="checkbox" checked={watch('trustServerCertificate')} onChange={(event) => setValue('trustServerCertificate', event.target.checked)}/><div><strong>Ufaj certyfikatowi serwera</strong></div></label></div>{message && <div className="settings-message">{message}</div>}<div className="settings-actions"><Button type="button" variant="secondary" onClick={() => void test()} disabled={testing}><PlugZap size={17}/>{testing ? 'Testowanie...' : 'Testuj połączenie'}</Button><Button type="submit">Zapisz ustawienia</Button></div></form></Card><div className="settings-aside"><Card className="security-card"><ShieldCheck size={23}/><h3>Dostęp tylko do odczytu</h3><p>Aplikacja wykonuje wyłącznie przygotowane zapytania SELECT. Hasło jest szyfrowane przez Windows.</p></Card><Card className="security-card project-folder-card"><FolderOpen size={23}/><h3>Folder projektów</h3><p>{settings?.projectsFolder ?? 'Ładowanie...'}</p><Button variant="secondary" onClick={() => void chooseFolder()}>Zmień folder</Button></Card></div></div></>
}
