import { z } from 'zod'

export const erpConfigSchema = z.object({ server: z.string().trim().min(1), database: z.string().trim().min(1), authenticationType: z.literal('sql'), username: z.string().trim().min(1), password: z.string().optional(), encrypt: z.boolean(), trustServerCertificate: z.boolean() })
export const productFilterSchema = z.object({ query: z.string().max(100).optional(), manufacturer: z.string().max(100).optional(), category: z.string().max(100).optional(), type: z.string().max(100).optional(), page: z.number().int().min(1).default(1), pageSize: z.number().int().min(1).max(100).default(25) })
export const productIdSchema = z.object({ gidNumer: z.number().int(), gidTyp: z.number().int().optional() })
export const catalogInputSchema = z.object({ id: z.string().uuid().optional(), name: z.string().trim().min(1).max(120), title: z.string().trim().min(1).max(160), subtitle: z.string().max(240), validFrom: z.string().nullable(), validTo: z.string().nullable() })
export const pageTypeSchema = z.enum(['COVER', 'TABLE_OF_CONTENTS', 'BRAND_PRODUCTS', 'PRODUCTS', 'PRODUCT_GRID_12', 'PRODUCT_GRID_16', 'BRANDS', 'CONTACTS', 'PROMOTION', 'TEXT', 'CUSTOM'])
export const productUnitSchema = z.object({ baseUnit: z.string(), displayUnit: z.string(), conversionNumerator: z.number().nullable(), conversionDenominator: z.number().nullable(), conversionFactor: z.number().nullable(), hasAlternativeUnit: z.boolean() })
export const productSchema = z.object({ id: z.string(), erpGidNumer: z.number().int(), erpGidTyp: z.number().int(), code: z.string(), ean: z.string().nullable(), name: z.string(), type: z.string().nullable(), group: z.string().nullable(), manufacturer: z.string().nullable(), brand: z.string().nullable(), category: z.string().nullable(), unit: productUnitSchema, weight: z.number().nullable(), itemsPerBox: z.number().nullable(), vatRate: z.number().nullable(), image: z.string().nullable(), stock: z.number().nullable(), active: z.boolean() })
export const catalogPageItemSchema = z.object({ id: z.string().uuid(), pageId: z.string().uuid(), slotKey: z.string().max(50), erpId: z.number().int(), erpProductGidNumer: z.number().int(), erpProductGidTyp: z.number().int(), sortOrder: z.number().int(), customData: z.record(z.string(), z.unknown()), overrides: z.object({ displayName: z.string().nullable(), weightLabel: z.string().nullable(), boxLabel: z.string().nullable(), customImage: z.string().nullable(), hiddenFields: z.array(z.string()) }), product: productSchema })
export const catalogPageSchema = z.object({ id: z.string().uuid(), catalogId: z.string().uuid(), pageType: pageTypeSchema, templateCode: z.string().max(50), sortOrder: z.number().int(), manufacturerRef: z.string().nullable(), configuration: z.record(z.string(), z.unknown()), enabled: z.boolean(), items: z.array(catalogPageItemSchema) })
export const catalogSchema = z.object({ schemaVersion: z.literal(1), id: z.string().uuid(), name: z.string().min(1), title: z.string(), subtitle: z.string(), validFrom: z.string().nullable(), validTo: z.string().nullable(), status: z.enum(['draft', 'published']), createdAt: z.string(), updatedAt: z.string(), settings: z.object({ pageFormat: z.literal('A4'), defaultBackground: z.string().nullable() }), pages: z.array(catalogPageSchema) })
export const qrInputSchema = z.object({ name: z.string().trim().min(1).max(120), url: z.url().max(1000), label: z.string().max(200) })
