const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const { randomUUID } = require('node:crypto')
const path = require('node:path')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText, filename)

const { FileProjectRepository } = require('../src/main/projects/FileProjectRepository.ts')
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'lechtom-project-'))
try {
  const repository = new FileProjectRepository({ get: () => ({ projectsFolder: directory }) })
  const catalog = repository.save({ name: 'Test', title: 'Oferta', subtitle: '', validFrom: null, validTo: null })
  assert.deepEqual(catalog.pages.map((page) => page.pageType), ['COVER', 'TABLE_OF_CONTENTS', 'PROMOTION', 'CONTACTS'])
  const pageId = randomUUID()
  repository.savePage({ id: pageId, catalogId: catalog.id, pageType: 'BRAND_PRODUCTS', templateCode: 'PRODUCT_GRID_12', sortOrder: 2, manufacturerRef: 'Hortex', configuration: {}, enabled: true, items: [] })
  const product = { id: '0:42', erpGidNumer: 42, erpGidTyp: 0, code: 'X', ean: '123', name: 'Produkt', type: 'Gastro', group: null, manufacturer: 'Hortex', brand: 'Hortex', category: 'Owoce', unit: { baseUnit: 'kg', displayUnit: 'kg', conversionNumerator: null, conversionDenominator: null, conversionFactor: null, hasAlternativeUnit: false }, weight: null, itemsPerBox: null, vatRate: 23, image: null, stock: null, active: true }
  repository.setPageItems(pageId, [{ id: randomUUID(), pageId, slotKey: 'product01', erpId: 42, erpProductGidNumer: 42, erpProductGidTyp: 0, sortOrder: 0, customData: {}, overrides: { displayName: null, weightLabel: null, boxLabel: null, customImage: null, hiddenFields: [] }, product }])
  const edited = repository.get(catalog.id).pages[2].items[0]
  repository.setPageItems(pageId, [{ ...edited, overrides: { ...edited.overrides, displayName: 'Nazwa w katalogu', customImage: 'lechtom-media://asset/local-image', hiddenFields: ['ean'] } }])
  const reopened = new FileProjectRepository({ get: () => ({ projectsFolder: directory }) }).get(catalog.id)
  assert.equal(reopened.pages[2].items[0].product.name, 'Produkt')
  assert.equal(reopened.pages[2].items[0].overrides.displayName, 'Nazwa w katalogu')
  assert.equal(reopened.pages[2].items[0].overrides.customImage, 'lechtom-media://asset/local-image')
  assert.deepEqual(reopened.pages[2].items[0].overrides.hiddenFields, ['ean'])
  assert.equal(reopened.pages.at(-1).pageType, 'CONTACTS')
  assert.equal(fs.existsSync(path.join(directory, catalog.id, 'project.json')), true)
  assert.equal(fs.existsSync(path.join(directory, catalog.id, 'project.json.tmp')), false)
  const copy = repository.duplicate(catalog.id)
  assert.notEqual(copy.id, catalog.id)
  assert.equal(copy.pages[2].items[0].product.name, 'Produkt')
  repository.delete(copy.id)
  repository.delete(catalog.id)
  assert.equal(repository.list().length, 0)
  console.log('File project persistence smoke test passed')
} finally { fs.rmSync(directory, { recursive: true, force: true }) }
