// Run with Electron's Node runtime so better-sqlite3 has the same ABI as the app.
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { randomUUID } = require('node:crypto')
const ts = require('typescript')
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }).outputText, filename)

const Database = require('better-sqlite3')
const { drizzle } = require('drizzle-orm/better-sqlite3')
const { migrate } = require('drizzle-orm/better-sqlite3/migrator')
const schema = require('../src/main/db/sqlite/schema.ts')
const { CatalogRepository } = require('../src/main/db/sqlite/CatalogRepository.ts')
const sqlite = new Database(':memory:')
const db = drizzle(sqlite, { schema })
migrate(db, { migrationsFolder: path.join(__dirname, '..', 'drizzle') })
const repository = new CatalogRepository(db)
const catalog = repository.save({ name: 'Test', title: 'Oferta', subtitle: '', validFrom: null, validTo: null })
assert.equal(catalog.pages.length, 1)
const pageId = randomUUID()
repository.savePage({ id: pageId, catalogId: catalog.id, pageType: 'PRODUCT_GRID_12', templateCode: 'PRODUCT_GRID_12', sortOrder: 1, manufacturerRef: 'Hortex', configuration: {}, enabled: true, items: [] })
repository.setPageItems(pageId, [{ id: randomUUID(), pageId, slotKey: 'product01', erpProductGidNumer: 42, erpProductGidTyp: 16, sortOrder: 0, customData: {} }])
assert.equal(repository.get(catalog.id).pages[1].items[0].erpProductGidNumer, 42)
repository.reorderPages(catalog.id, [pageId, catalog.pages[0].id])
assert.equal(repository.get(catalog.id).pages[0].id, pageId)
repository.save({ id: catalog.id, name: 'Test 2', title: 'Oferta', subtitle: '', validFrom: null, validTo: null })
assert.equal(repository.get(catalog.id).name, 'Test 2')
repository.delete(catalog.id)
assert.equal(repository.list().length, 0)
sqlite.close()
console.log('Catalog SQLite CRUD smoke test passed')
