import { integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'

const timestamps = { createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() }
export const catalogs = sqliteTable('catalogs', { id: text('id').primaryKey(), name: text('name').notNull(), title: text('title').notNull(), subtitle: text('subtitle').notNull().default(''), validFrom: text('valid_from'), validTo: text('valid_to'), status: text('status').notNull().default('draft'), ...timestamps })
export const catalogPages = sqliteTable('catalog_pages', { id: text('id').primaryKey(), catalogId: text('catalog_id').notNull().references(() => catalogs.id, { onDelete: 'cascade' }), pageType: text('page_type').notNull(), templateCode: text('template_code').notNull(), sortOrder: integer('sort_order').notNull(), manufacturerRef: text('manufacturer_ref'), configuration: text('configuration', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default({}), enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true) })
export const catalogPageItems = sqliteTable('catalog_page_items', { id: text('id').primaryKey(), pageId: text('page_id').notNull().references(() => catalogPages.id, { onDelete: 'cascade' }), slotKey: text('slot_key').notNull(), erpProductGidNumer: integer('erp_product_gid_numer').notNull(), erpProductGidTyp: integer('erp_product_gid_typ').notNull(), sortOrder: integer('sort_order').notNull(), customData: text('custom_data', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default({}) })
export const pageTemplates = sqliteTable('page_templates', { id: text('id').primaryKey(), code: text('code').notNull().unique(), name: text('name').notNull(), pageType: text('page_type').notNull(), slots: text('slots', { mode: 'json' }).$type<string[]>().notNull().default([]) })
export const manufacturerPresentations = sqliteTable('manufacturer_presentations', { id: text('id').primaryKey(), erpReference: text('erp_reference').notNull().unique(), displayName: text('display_name').notNull(), logoAssetId: text('logo_asset_id'), sortOrder: integer('sort_order').notNull().default(0), catalogEnabled: integer('catalog_enabled', { mode: 'boolean' }).notNull().default(true), defaultTemplate: text('default_template') })
export const productPresentations = sqliteTable('product_presentations', { id: text('id').primaryKey(), erpGidNumer: integer('erp_gid_numer').notNull(), erpGidTyp: integer('erp_gid_typ').notNull(), customImageAssetId: text('custom_image_asset_id'), customMarketingName: text('custom_marketing_name'), customDescription: text('custom_description'), hiddenInCatalog: integer('hidden_in_catalog', { mode: 'boolean' }).notNull().default(false), preferredTemplate: text('preferred_template'), sortOrder: integer('sort_order').notNull().default(0), ...timestamps }, (t) => [uniqueIndex('product_presentation_erp_id').on(t.erpGidNumer, t.erpGidTyp)])
export const mediaAssets = sqliteTable('media_assets', { id: text('id').primaryKey(), filename: text('filename').notNull(), originalFilename: text('original_filename').notNull(), mimeType: text('mime_type').notNull(), path: text('path').notNull(), width: integer('width'), height: integer('height'), fileSize: integer('file_size').notNull(), createdAt: text('created_at').notNull() })
export const qrCodes = sqliteTable('qr_codes', { id: text('id').primaryKey(), name: text('name').notNull(), url: text('url').notNull(), label: text('label').notNull(), svg: text('svg').notNull(), createdAt: text('created_at').notNull() })
export const contactLocations = sqliteTable('contact_locations', { id: text('id').primaryKey(), name: text('name').notNull(), address: text('address').notNull(), phone: text('phone'), email: text('email'), sortOrder: integer('sort_order').notNull().default(0) })
export const catalogSettings = sqliteTable('catalog_settings', { key: text('key').primaryKey(), value: text('value', { mode: 'json' }).$type<unknown>().notNull() })
